### ISSUE TITLE
LAshow: Garbage .las file, trace spacing <= 0

### ISSUE THREAD

**Issue by orangeSi** [thegenemyers/DASCRUBBER#1]
Dear Dr. Myers,
        when I generate new .las with DASCRUBBER(DASrealign)  ,then  when I run: LAshow bac.new bac.new  bac.all.new.las,I get an error:LAshow: Garbage .las file, trace spacing <= 0!

Thanks~
Si

**Comment by orangeSi** [comment]
I update the LAshow ,then the error disapear~

**Comment by thegenemyers** [comment]
You need to download a new version of the DALIGNER module that contains 
a new
version of LAshow that can handle the output of the scrubber.
    -- Gene

**Comment by orangeSi** [comment]
Thanks~

2017-05-14 20:08 GMT+08:00 Eugene W Myers Jr <notifications@github.com>:
