### ISSUE TITLE
Make a release for packaging purposes?

### ISSUE THREAD

**Issue by tseemann** [thegenemyers/DASCRUBBER#13]
Gene,

I'd like to write a Conda and Brew package to enable people to easily install DASCRUBBER.

However, it needs to have an official "Release" using the Releases tab:
https://github.com/thegenemyers/DASCRUBBER/releases

Or, at least a *named* `git tag` to refer too.

The release can just be simple like version 0.1 and can be ticked as "pre-release", any of these would help.

Thanks,

Torsten

**Comment by thegenemyers** [comment]
OK, I did so.  Is there anyway to always have the most reason version tagged?
As it is, it seems I have to inefficiently create a new tag with every updage.
Please advise.  Gene

**Comment by tseemann** [comment]
The commit hash can also be used as "tag", but it is strongly discouraged because you can change git history.

But the idea of releases is that it has been labelled "stable" by the author, and exists as a single .tar.gz that can be archived and sha256 checked.
