### ISSUE TITLE
Crash in Catrack

### ISSUE THREAD

**Issue by gt1** [thegenemyers/DASCRUBBER#14]
Hello Gene,

in Catrack, when the number of input block tracks is smaller than the number of blocks in the database the program crashes because it calls fclose(aout) on a file descriptor which has already been closed using FCLOSE(aout). 

Best,
German

**Comment by thegenemyers** [comment]
Thanks, fixed it, it will be in the next github checkin which should be 
very soon.
Since it  was about to report an error message anyway, I'm presuming you can
wait :-)

    -- Gene
