### ISSUE TITLE
Adapting scrubbed reads as input to FALCON-Unzip for Arrow polishing

### ISSUE THREAD

**Issue by lautimothy** [thegenemyers/DASCRUBBER#18]
FALCON-Unzip currently requires unaligned bam files as input for genomic consensus / phased-polishing with Arrow.  However, DASedit only transfers the sequence information (i.e. no arrow info) to the new scrubbed database and relies on DASmap to provide mapping information from old reads to new scrubbed reads.  While scrubbed fasta can be used as input to FALCON for assembly, we are not sure what unaligned bam files containing pulse width info to use for FALCON-Unzip.  There are 2 approaches:

(1) use original (unscrubbed) unaligned bam files
(2) reconstruct unaligned bam files representing scrubbed reads using mapping information (DASmap output) and original bam files.

Which approach would you think is more suitable? Would using approach (1) mess up the assembly (from scrubbed reads) in anyway or undo some of the effort from scrubbing?

Regarding approach (2), we were wondering for each subread:
(i) how would one provide the pulse width information for the patched segments
(ii) can one just cut and re-join the pulse width values for the other segments
(iii) do the SNR values stay the same before and after scrubbing.

Many thanks,
Tim

**Comment by thegenemyers** [comment]
Hi Tim,

     My understanding is that the pulse width information is needed 
really only by Arrow to
produce a consensus at the end of assembly.  No assembler I know of uses 
the pulse widths
to make decision about individual overlaps and/or path traversals within 
the string graph and
I believe this includes Falcon.

     So I only forward the edited (and hopefully improved) sequence 
forward for assembly.
Once a tiling of edited reads in a contig has been decided upon by an 
assembler, then at
that point I would use the mapping to go back and get the relevant raw 
read (with pulse info)
and align it to the first level consensus with produced with the edited 
reads, and then let
Arrow refine the consensus.

    -- Gene

**Comment by lautimothy** [comment]
Thank you for the reply.  If I understand you correctly, Arrow will only make decisions regarding individual bases' consensus, but not with whole segments of the assembly.  So you don't think the unscrubbed part of the raw read would affect the consensus refining process when it is aligned to the first level consensus?

**Comment by thegenemyers** [comment]
I wouldn't use the unscrubbed portion in producing the consensus in a 
given region
unless there just otherwise isn't sufficient covereage of it.  My point 
is that the details
of alignment between the scrubbed and unscrubbed read don't need to be 
kept, just
the corresponding segments.  One would use these to produce a crude 
initial multi-alignment
of the unscrubbed data that then gets passed to Arrow to refine.
    -- Gene

**Comment by lautimothy** [comment]
Got it.  Thank you for the fast response.
