### ISSUE TITLE
DASqv -v -c20 bac bac.all >histogram,help about the histogram~

### ISSUE THREAD

**Issue by orangeSi** [thegenemyers/DASCRUBBER#2]
Dear Dr.Myers:
     When I run:DASqv -v -c20 bac bac.all >histogram,then get this:

Input:   12,999reads,   112,500,072 bases

Histogram of q-values (average 10 best)

                 Input                 QV

    50:      56581    0.2%       154629   13.7%

    49:      12656    0.0%          497    0.1%
    48:      17962    0.1%          559    0.1%
    47:      22024    0.2%          606    0.2%
    46:      27501    0.3%          688    0.2%
    45:      34074    0.4%          826    0.3%
    44:      42695    0.6%          918    0.4%
    43:      53491    0.8%         1083    0.5%
    42:      64855    1.0%         1357    0.7%
    41:      79309    1.3%         1594    0.8%
    40:     106927    1.7%         1892    1.0%
    39:     105199    2.1%         2195    1.3%
    38:     139048    2.6%         2596    1.5%
    37:     169499    3.2%         2978    1.8%
    36:     198652    4.0%         3617    2.2%
    35:     238621    4.8%         4081    2.6%
    34:     282588    5.9%         4957    3.1%
    33:     326866    7.1%         5801    3.7%
    32:     396516    8.6%         6800    4.4%
    31:     455270   10.2%         8137    5.2%
    30:     545035   12.3%         9763    6.2%
    29:     622061   14.6%        11644    7.4%
    28:     723821   17.2%        14066    8.9%
    27:     850777   20.4%        17129   10.6%
    26:     974205   24.0%        21071   12.8%
    25:    1157496   28.3%        25595   15.4%
    24:    1186911   32.6%        31175   18.6%
    23:    1387918   37.8%        37510   22.4%
    22:    1507814   43.3%        44691   27.0%
    21:    1631860   49.4%        53076   32.4%
    20:    1751877   55.8%        61513   38.7%
    19:    1708621   62.1%        70594   46.0%
    18:    1747792   68.6%        77733   53.9%
    17:    1685610   74.8%        82742   62.4%
    16:    1560937   80.6%        83827   71.0%
    15:    1379207   85.7%        78971   79.1%
    14:    1158417   90.0%        68337   86.1%
    13:     916598   93.4%        53641   91.6%
    12:     682017   95.9%        37375   95.4%
    11:     471013   97.6%        23037   97.7%
    10:     301563   98.7%        12300   99.0%
     9:     174920   99.4%         5661   99.6%
     8:      94230   99.7%         2536   99.8%
     7:      43065   99.9%         1008   99.9%
     6:      18799  100.0%          412  100.0%
     5:       6759  100.0%          140  100.0%
     4:       3155  100.0%           45  100.0%
     3:        863  100.0%           11  100.0%
     2:        193  100.0%            7  100.0%
     1:         12  100.0%            1  100.0%
     0:        247  100.0%            4  100.0%

for example（   49:      12656    0.0%          497    0.1%），I don't understand the mean of every column of that.

Thanks~
Si

**Comment by thegenemyers** [comment]
The  "Input" histogram is the histogram of all the trace point 
differences between A and B
reads, whereas the QV histogram is of all the computed QV statistics of 
A trace-point
intervals.  You pick the -g and -b thresholds for DAStrim using the QV 
histogram.  The
percentages are hopefully obvious -- the cumulative percentage of the 
data at or above
the given row level.
    -- Gene

**Comment by orangeSi** [comment]
thanks~
So -g and -b for DAStrim should be determined by second and third column ?
for that histogram, -g27 -b 34 may be proper ?

2017-05-14 20:12 GMT+08:00 Eugene W Myers Jr <notifications@github.com>:

**Comment by orangeSi** [comment]
anothor qustion:
1.First I got 20x subreads for 5M genome bacteria,then run
DB2fasta->DBsplit->daligner -> LA4Falcon -> fc_consensus.py ->celera
assembly.
2.Second,with the sam 20x subread ,I run DB2fasta->DBsplit->daligner ->
DASqv->DAStrim->DASpatch->DASedit->daligner (again)->LA4Falcon ->
fc_consensus.py ->celera assembly ,get longer corrected subreads ,but worse
N50 of assembly result.This is the detail code:

. /share/backup/sikaiwei/sikaiwei/assembly/Gene_Myers/env.sh
pre=bac
fasta=xx.rename.subread.fasta
fasta2DB $pre $fasta &&
DBsplit -x500 -s50  $pre &&
B1=$(cat $pre.db | awk '$1 == "blocks" {print $3}') &&
HPC.daligner -v -t16 -e.70  -s100 -H1000 $pre 1-$B1 >run_jobs.sh &&
sh run_jobs.sh &&
LAmerge -v $pre.all $pre.[1-$B1] &&
DASqv -c20 $pre $pre.all
DAStrim -g27 -b34  $pre $pre.all &&
DASpatch $pre $pre.all &&
DASedit  $pre $pre.new  &&
HPC.daligner -v -t16 -e.70  -s100 -H1000 $pre.new 1-$B1 >run_jobs.new.sh  &&
sh run_jobs.new.sh &&
for i in $(seq 1 1 $B1)
do
    . Falcon_unzip/fc_env/bin/activate &&
    LA4Falcon -H2000 -fo $pre.new.db bac.new.$i.las|  fc_consensus.py
--output_full --min_idt 0.70 --min_cov 5 --min_cov_aln 0 --max_n_read 200
--n_core 4  > $pre.new.$i.las.untrimmed.fa
done
echo done


Help~
Si

2017-05-14 21:45 GMT+08:00 orange si <ilikeorangeapple@gmail.com>:

**Comment by thegenemyers** [comment]
No !  Use the 4th and 5th columns which reflect the QV scores, -g23 and 
-b30 would be more appropriate.
    -- Gene

**Comment by thegenemyers** [comment]
Your DAStrim parameters are way off.  I would imagine -g22 -b30 would 
work much
better.  That is the basic problem.

I also would not use -t16, but rather -M16 (assuming you have a 16Gb 
memory), and
I'm not sure why you use -H1000 for daligner and -H2000 for Falcon.

    -- Gene

**Comment by orangeSi** [comment]
thanks,I will try yours parameter.
And -H1000 of daligner is for only keep overlap that's longer than 1000bp,-H2000 of falcon is for only correct reads that's longer than 2000bp,do you have some advice for that?
