### ISSUE TITLE
DASqv: Cannot open ./foo.las for 'r'

### ISSUE THREAD

**Issue by agroppi** [thegenemyers/DASCRUBBER#3]
I followed the pipeline : 
dex2DB ==> DBsplit ==> TANmask ==> REPmask ==> daligner (HPC.daligner)
Now I'm launching the first step of scrubbing
But DASqv give me the following error : 
`DASqv: Cannot open ./file.las for 'r'`

My command : 
`DASqv -v -c70 foo foo`

In the working directoty I have:
```
foo.[1-N].las files
foo.db
.foo.idx
.foo.bps
```

What is going wrong ?
Thanks for your help

Cheers from France

**Comment by agroppi** [comment]
I found the "bug" :/
The right command should be : 
`DASqv -v -c70 foo.db foo.*.las`

**Comment by thegenemyers** [comment]
Yes, exactly.  Cheers, Gene
