### ISSUE TITLE
Segmentation fault using DASedit

### ISSUE THREAD

**Issue by ngirollet** [thegenemyers/DASCRUBBER#4]
Dear Dr Myers,
Discontinuity in quality of Pacbio sequences made me wonder to develop a tool for dealing this local heterogeneity until i discovered your DASCRUBBER repository. Many thanks for sharing this work.
I've followed this pipeline on las files produced by the first steps of Falcon Assembly  (DASqv -v -c80; DAStrim -v -g21 -b26; DASpatch -v ; DASedit -v). Unfortunately, on this last stage, i can't answer by myself to the meaning of the -x parameter and more i'm facing a segmentation fault  for which i have no clue to solve this. 

Is it possible to have some specs or tips on the ressources needed/attention to pay/prerequisits to have for dealing whith the DASedit module ?

Here some info that might be useful : 
**lscpu** 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
**free -tg** Mem total : 252G
**ls -alh** 
-rw-r--r--   1 ngirollet VVEGFV  13G Jan  9  2017 .raw_reads.bps
-rw-r--r--   1 ngirollet VVEGFV  12K Jan  9  2017 raw_reads.db
-rw-rw-r--   1 ngirollet VVEGFV  57M Sep 26 11:19 .raw_reads.patch.anno
-rw-rw-r--   1 ngirollet VVEGFV  71M Sep 26 11:19 .raw_reads.patch.data
-rw-rw-r--   1 ngirollet VVEGFV  57M Sep 26 09:46 .raw_reads.qual.anno
-rw-rw-r--   1 ngirollet VVEGFV 508M Sep 26 09:46 .raw_reads.qual.data
-rw-rw-r--   1 ngirollet VVEGFV  57M Sep 26 10:56 .raw_reads.trim.anno
-rw-rw-r--   1 ngirollet VVEGFV  90M Sep 26 10:56 .raw_reads.trim.data

Many thanks for your time in answering this issue.
Best regards,

**Comment by ngirollet** [comment]
Hello again,
I 've ran DASedit on a computer with /var/log/syslog read access and  noticed : 
`traps: DASedit[29055] general protection ip:7fc9ddaca513 sp:7ffe9f187f38 error:0 in libc-2.23.so[7fc9dda36000+1c0000] `

On a second hand, i used gdb on DASedit as follow : 
```
gdb DASedit
(gdb) run -v raw_reads.db raw_reads_scrub.db
Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2 () at ../sysdeps/x86_64/multiarch/../memcpy.S:167
167	../sysdeps/x86_64/multiarch/../memcpy.S: Aucun fichier ou dossier de ce type.
```
Hope it helps ...

**Comment by thegenemyers** [comment]
This could be hard to debug without a test case.  But for now, recompile 
DASedit with the -g option
set.  Then run in lldb and when you get to the segfault please request a 
backtrace with the "bt" command.
That might be enough to understand the problem (albeit most likely not).

The -x parameter requests that all scrubbed reads less than the 
specified length (in the -x parameter) are
not included in the database.

    -- Gene

**Comment by ngirollet** [comment]
Indeed, that's what i've done and noticed DASedit was stuttering after some iterations with no straight errors nor in the code nor in the return of strace, ltrace or backtrace debug. Here, i've used the more up to date Catrack module and this seems solved the 'bug' ... I can't explain any further the 'how' and 'why' :-\
Thanks anyway for your reply and my apologies for this non relevant issue.

**Comment by diriano** [comment]
Dear Dr. Myers,

I have run the scrubber pipeline (DASqv -v -c80; DAStrim -v -g22 -b28; DASpatch -v ; DASedit -v), on data that was previously processed with DAMAPPER as per the instructions in your blog. 
DASedit is dying as reported in this post. I have run lldb and below you find the backtrace (bt command). I am using the latest code from github.

I have run, to the same exact results, on two different servers with linux: CenOS 7.4.1708 and Red Hat 6.5. The RH server is a SGI machine with 1.7TB RAM and 280 cores.

Any hints on what could be happening?

Thanks a lot in advance.

$ lldb
(lldb) file /data/SCRUBBING_Software/bin/DASedit
(lldb) run -v reads/Vintermedia_DB scrubbed_reads/Vintermedia_CleanDBb
Process 14562 launched: '/data/SCRUBBING_Software/bin/DASedit' (x86_64)
Process 14562 stopped
* thread #1: tid = 14562, 0x00007fb100a399c3 libc.so.6`__GI___mempcpy + 147, name = 'DASedit', stop reason = invalid address (fault address: 0x0)
    frame #0: 0x00007fb100a399c3 libc.so.6`__GI___mempcpy + 147
libc.so.6`__GI___mempcpy + 147:
-> 0x7fb100a399c3:  movb   %al, (%rdi)
   0x7fb100a399c5:  incl   %ecx
   0x7fb100a399c7:  leaq   0x1(%rsi), %rsi
   0x7fb100a399cb:  leaq   0x1(%rdi), %rdi
(lldb) bt
* thread #1: tid = 14562, 0x00007fb100a399c3 libc.so.6`__GI___mempcpy + 147, name = 'DASedit', stop reason = invalid address (fault address: 0x0)
  * frame #0: 0x00007fb100a399c3 libc.so.6`__GI___mempcpy + 147
    frame #1: 0x00007fb100a2642e libc.so.6`_IO_file_xsgetn + 382
    frame #2: 0x00007fb100a1ba7f libc.so.6`__GI__IO_fread + 143
    frame #3: 0x00000000004194ec DASedit`Load_Subread(db=<unavailable>, i=<unavailable>, beg=3941, end=<unavailable>, read=0x0038efd800487b7c, ascii=0) + 172 at DB.c:1721
    frame #4: 0x0000000000402775 DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb1012661a4, depth=<unavailable>) + 101 at DASedit.c:133
    frame #5: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb1012653b0, depth=<unavailable>) + 282 at DASedit.c:146
    frame #6: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101264575, depth=<unavailable>) + 282 at DASedit.c:146
    frame #7: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101263781, depth=<unavailable>) + 282 at DASedit.c:146
    frame #8: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101262946, depth=<unavailable>) + 282 at DASedit.c:146
    frame #9: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101261b52, depth=<unavailable>) + 282 at DASedit.c:146
    frame #10: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101260d17, depth=<unavailable>) + 282 at DASedit.c:146
    frame #11: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10125ff23, depth=<unavailable>) + 282 at DASedit.c:146
    frame #12: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb10125f0e8, depth=<unavailable>) + 282 at DASedit.c:146
    frame #13: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10125e2f4, depth=<unavailable>) + 282 at DASedit.c:146
    frame #14: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb10125d4b9, depth=<unavailable>) + 282 at DASedit.c:146
    frame #15: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10125c6c5, depth=<unavailable>) + 282 at DASedit.c:146
    frame #16: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb10125b88a, depth=<unavailable>) + 282 at DASedit.c:146
    frame #17: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10125aa96, depth=<unavailable>) + 282 at DASedit.c:146
    frame #18: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101259c5b, depth=<unavailable>) + 282 at DASedit.c:146
    frame #19: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101258e67, depth=<unavailable>) + 282 at DASedit.c:146
    frame #20: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb10125802c, depth=<unavailable>) + 282 at DASedit.c:146
    frame #21: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101257238, depth=<unavailable>) + 282 at DASedit.c:146
    frame #22: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb1012563fd, depth=<unavailable>) + 282 at DASedit.c:146
    frame #23: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101255609, depth=<unavailable>) + 282 at DASedit.c:146
    frame #24: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb1012547ce, depth=<unavailable>) + 282 at DASedit.c:146
    frame #25: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb1012539da, depth=<unavailable>) + 282 at DASedit.c:146
    frame #26: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101252b9f, depth=<unavailable>) + 282 at DASedit.c:146
    frame #27: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101251dab, depth=<unavailable>) + 282 at DASedit.c:146
    frame #28: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101250f70, depth=<unavailable>) + 282 at DASedit.c:146
    frame #29: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10125017c, depth=<unavailable>) + 282 at DASedit.c:146
    frame #30: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb10124f341, depth=<unavailable>) + 282 at DASedit.c:146
    frame #31: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10124e54d, depth=<unavailable>) + 282 at DASedit.c:146
    frame #32: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb10124d712, depth=<unavailable>) + 282 at DASedit.c:146
    frame #33: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10124c91e, depth=<unavailable>) + 282 at DASedit.c:146
    frame #34: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb10124bae3, depth=<unavailable>) + 282 at DASedit.c:146
    frame #35: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10124acef, depth=<unavailable>) + 282 at DASedit.c:146
    frame #36: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101249eb4, depth=<unavailable>) + 282 at DASedit.c:146
    frame #37: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb1012490c0, depth=<unavailable>) + 282 at DASedit.c:146
    frame #38: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101248285, depth=<unavailable>) + 282 at DASedit.c:146
    frame #39: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101247491, depth=<unavailable>) + 282 at DASedit.c:146
    frame #40: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101246656, depth=<unavailable>) + 282 at DASedit.c:146
    frame #41: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101245862, depth=<unavailable>) + 282 at DASedit.c:146
    frame #42: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101244a27, depth=<unavailable>) + 282 at DASedit.c:146
    frame #43: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101243c33, depth=<unavailable>) + 282 at DASedit.c:146
    frame #44: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101242df8, depth=<unavailable>) + 282 at DASedit.c:146
    frame #45: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101242004, depth=<unavailable>) + 282 at DASedit.c:146
    frame #46: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb1012411c9, depth=<unavailable>) + 282 at DASedit.c:146
    frame #47: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb1012403d5, depth=<unavailable>) + 282 at DASedit.c:146
    frame #48: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb10123f59a, depth=<unavailable>) + 282 at DASedit.c:146
    frame #49: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10123e7a6, depth=<unavailable>) + 282 at DASedit.c:146
    frame #50: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb10123d96b, depth=<unavailable>) + 282 at DASedit.c:146
    frame #51: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10123cb77, depth=<unavailable>) + 282 at DASedit.c:146
    frame #52: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb10123bd3c, depth=<unavailable>) + 282 at DASedit.c:146
    frame #53: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10123af48, depth=<unavailable>) + 282 at DASedit.c:146
    frame #54: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb10123a10d, depth=<unavailable>) + 282 at DASedit.c:146
    frame #55: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101239319, depth=<unavailable>) + 282 at DASedit.c:146
    frame #56: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb1012384de, depth=<unavailable>) + 282 at DASedit.c:146
    frame #57: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb1012376ea, depth=<unavailable>) + 282 at DASedit.c:146
    frame #58: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb1012368af, depth=<unavailable>) + 282 at DASedit.c:146
    frame #59: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101235abb, depth=<unavailable>) + 282 at DASedit.c:146
    frame #60: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101234c80, depth=<unavailable>) + 282 at DASedit.c:146
    frame #61: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb101233e8c, depth=<unavailable>) + 282 at DASedit.c:146
    frame #62: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0ec0034b0, target=0x00007fb101233051, depth=<unavailable>) + 282 at DASedit.c:146
    frame #63: 0x000000000040282a DASedit`Load_Model(patch=0x00007fb0e6e4e9dc, target=0x00007fb10123225d, depth=<unavailable>) + 282 at DASedit.c:146
    frame #64: 0x0000000000401f01 DASedit`main(argc=<unavailable>, argv=<unavailable>) + 3745 at DASedit.c:570
    frame #65: 0x00007fb1009d1c05 libc.so.6`__libc_start_main + 245
