### ISSUE TITLE
 DASpatch reports trim annotation is out of date

### ISSUE THREAD

**Issue by LizzieMcDizzie** [thegenemyers/DASCRUBBER#5]
Hi
Firstly, thank you for the package, I have pointed a number of people to your blog to help them understand what falcon is actually doing - it is very under appreciated in my opinion.
I am trying to scrub reads to improve my falcon assembly of a mammalian genome. I have made it to the patch step and can not interpret the error given by DASpatch about the trim track.
I was hoping you could point me towards what may cause DASpatch to report the error:

> DASpatch: trim annotation is out of date, rerun DAStrim

I have run DAStrim twice, it appears to complete without any errors, but DASpatch gives this error for all db segments.
Sorry for the basic question.  If you need any specific details please let me know.

Thank you.

**Comment by thegenemyers** [comment]
I added pass-thru of the input parameters to DASqv and DAStrim that is the basic source
of the problem.  Could you please redownload and build all the programs of the scrubber
module, and then try rerunning the pipeline *starting at the beginning with DASqv*.  If that
still doesn't work get back to me.

Incidently, I have observed some non-optimal behavior on genomes that have highly
heterogeneous haplotypes, and I will be fixing this soon.  Also if you are PB, then I'll
be through the week of Jan 15-19.

**Comment by LizzieMcDizzie** [comment]
Hi,
I have downloaded, installed and rerun DASqv, DAStrim and finally DASpatch and the same error appears.
I am using:
`DASqv -v -H5000 -c65 raw_reads raw_reads.${PBS_ARRAY_INDEX}.las` 
`DAStrim -v -g20 -b25 raw_reads raw_reads.${PBS_ARRAY_INDEX}.las`
`DASpatch -v raw_reads raw_reads.${PBS_ARRAY_INDEX}.las`

${PBS_ARRAY_INDEX} is just used to call the block number for use with out HPC.  Of course I use Catrack in between each step.

This is a breed of domestic cattle and so I would be surprised if it was highly herterozygous compared to other things that you are assembling. We assume the genome is ~3gb, we have ~200gb of sequence data. 

Sorry I am not sure what you mean by 'if you are PB' - but if you are asking if I work at pacBio then no, I am in Australia.

Thank you for your time.

**Comment by LizzieMcDizzie** [comment]
An update:
I may have solved this mystery, I think the issue may have been using an old version of Catrack (in particular the once packaged with falcon) - the version I was using I assume was not passing along the input parameters of the blocks to the final trim track. 

The solution - download the most recent Catrack and use that. It appears to be working now (at least making .patch files that have something in them).

Cheers,
Liz

**Comment by thegenemyers** [comment]
Yes, that's right!  Well done, and sorry I didn't realize it myself.  -- 
Gene
