### ISSUE TITLE
Catrack: System error, read failed!

### ISSUE THREAD

**Issue by mictadlo** [thegenemyers/DASCRUBBER#9]
Hi,
I got the following error.

```
> Catrack -v plant trim 
...
Concatenating ./.plant.99.trim ...
Concatenating ./.plant.100.trim ...
Catrack: System error, read failed!
```
How is it possible to fix it?

Thank you in advance.

Michal

**Comment by mictadlo** [comment]
The problem was that I used DAStrim a file which did not exist and therefore it produced a wrong output.

**Comment by thegenemyers** [comment]
Most likely is it because either .plant.100.trim or then next one 
.plant.101.trim
is somehow corrupted or incomplete.
    -- Gene

**Comment by mictadlo** [comment]
Thank you.
